name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: make
      run: make
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: make test

  clean:
    runs-on: ubuntu-latest
    steps:
    - name: clean
      run: make clean
